In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = "https://www.football-data.co.uk/englandm.php"

In [3]:
data = requests.get(url)

In [4]:
soup = BeautifulSoup(data.text)

In [11]:
# Define the base URL and the season numbers
base_url = "https://www.football-data.co.uk/mmz4281/{}/E0.csv"
seasons = ["1314","1415","1516","1617","1718","1819", "1920","2021","2122", "2223", "2324"] # Add more seasons as needed

# Loop through the seasons and scrape the csv files
for season in seasons:
    url = base_url.format(season)
    response = requests.get(url)
    with open(f"./data/Premier_League_{season}.csv", "wb") as f:
        f.write(response.content)

In [13]:
df = pd.read_csv("./data/Premier_League_1314.csv")

In [14]:
# check column names
df.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2',
       'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU',
       'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [15]:
columns_to_select = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A']

In [17]:
import os

# Define the directory where the CSV files are located
directory = "./data"

# Get the list of CSV files in the directory
csv_files = [file for file in os.listdir(directory) if file.endswith(".csv")]

# Iterate through each CSV file
for file in csv_files:
    file_path = os.path.join(directory, file)
    df = pd.read_csv(file_path)
    
    # Check if all columns in columns_to_select exist in the dataframe
    if all(column in df.columns for column in columns_to_select):
        print(f"{file} contains all columns")
    else:
        print(f"{file} is missing some columns")

football_data.csv is missing some columns
matches.csv is missing some columns
matches_18_23.csv is missing some columns
Premier_League_1314.csv contains all columns
Premier_League_1415.csv contains all columns
Premier_League_1516.csv contains all columns
Premier_League_1617.csv contains all columns
Premier_League_1718.csv contains all columns
Premier_League_1819.csv contains all columns
Premier_League_1920.csv contains all columns
Premier_League_2021.csv contains all columns
Premier_League_2122.csv contains all columns
Premier_League_2223.csv contains all columns
Premier_League_2324.csv contains all columns

In [18]:
import pandas as pd

base_url = "./data/Premier_League_{}.csv"
seasons = ["1314","1415","1516","1617","1718","1819", "1920","2021","2122", "2223", "2324"]  # Add more seasons as needed
year = []

# Create an empty list to store the dataframes
dfs = []

# Loop through the seasons and read the csv files
for season in seasons:
    file_path = base_url.format(season)
    df = pd.read_csv(file_path, usecols=columns_to_select)
    # Add a column with the season number that is determined my seaons first two digit , so it should be 23 -> 2023
    df["Season"] = "20" + season[:2]

    dfs.append(df)

# Concatenate the dataframes on index
result = pd.concat(dfs, ignore_index=True)

In [19]:
result.shape

(3921, 26)

In [20]:
result

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,Season
0,17/08/13,Arsenal,Aston Villa,1.0,3.0,A,1.0,1.0,D,A Taylor,...,4.0,3.0,4.0,5.0,1.0,0.0,1.44,4.75,8.00,2013
1,17/08/13,Liverpool,Stoke,1.0,0.0,H,1.0,0.0,H,M Atkinson,...,12.0,6.0,1.0,1.0,0.0,0.0,1.40,5.00,9.50,2013
2,17/08/13,Norwich,Everton,2.0,2.0,D,0.0,0.0,D,M Oliver,...,6.0,8.0,2.0,0.0,0.0,0.0,3.20,3.40,2.40,2013
3,17/08/13,Sunderland,Fulham,0.0,1.0,A,0.0,0.0,D,N Swarbrick,...,6.0,1.0,0.0,3.0,0.0,0.0,2.30,3.40,3.40,2013
4,17/08/13,Swansea,Man United,1.0,4.0,A,0.0,2.0,A,P Dowd,...,7.0,4.0,1.0,3.0,0.0,0.0,4.20,3.50,2.00,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3916,12/11/2023,Aston Villa,Fulham,3.0,1.0,H,2.0,0.0,H,S Hooper,...,2.0,2.0,2.0,5.0,0.0,0.0,1.57,4.20,5.50,2023
3917,12/11/2023,Brighton,Sheffield United,1.0,1.0,D,1.0,0.0,H,J Brooks,...,6.0,3.0,3.0,2.0,1.0,0.0,1.25,5.75,13.00,2023
3918,12/11/2023,Liverpool,Brentford,3.0,0.0,H,1.0,0.0,H,P Tierney,...,6.0,8.0,1.0,2.0,0.0,0.0,1.40,5.00,6.50,2023
3919,12/11/2023,West Ham,Nott'm Forest,3.0,2.0,H,1.0,1.0,D,M Salisbury,...,9.0,4.0,2.0,2.0,0.0,0.0,1.85,3.60,4.00,2023
3920,12/11/2023,Chelsea,Man City,4.0,4.0,D,2.0,2.0,D,A Taylor,...,3.0,3.0,5.0,3.0,0.0,0.0,5.00,3.70,1.73,2023

In [21]:
result.groupby("Season").count()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A
Season,,,,,,,,,,,,,,,,,,,,,
2013,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2014,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2015,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2016,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2017,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2018,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2019,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2020,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2021,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2022,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
2023,120,120,120,120,120,120,120,120,120,120,...,120,120,120,120,120,120,120,120,120,120

In [22]:
# save the data
result.to_csv("./data/football_data.csv", index=False)