In [4]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [8]:
url = "https://www.football-data.co.uk/englandm.php"

In [9]:
data = requests.get(url)

In [10]:
soup = BeautifulSoup(data.text)

In [20]:
# Define the base URL and the season numbers
base_url = "https://www.football-data.co.uk/mmz4281/{}/E0.csv"
seasons = ["1820", "1920","2021","2122", "2223", "2324"] # Add more seasons as needed

# Loop through the seasons and scrape the csv files
for season in seasons:
    url = base_url.format(season)
    response = requests.get(url)
    with open(f"./data/Premier_League_{season}.csv", "wb") as f:
        f.write(response.content)

In [6]:
df = pd.read_csv("./data/Premier_League_1820.csv")

In [16]:
# we just want the prices
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [7]:
columns_to_select = ['Date','Time','HomeTeam','AwayTeam','B365H','B365D','B365A','B365>2.5','B365<2.5','PSH','PSD','PSA','P>2.5','P<2.5']

,Date,Time,HomeTeam,AwayTeam,B365H,B365D,B365A,B365>2.5,B365<2.5,PSH,PSD,PSA,P>2.5,P<2.5
0,09/08/2019,20:00,Liverpool,Norwich,1.14,10.00,19.00,1.40,3.00,1.15,9.59,18.05,1.40,3.11
1,10/08/2019,12:30,West Ham,Man City,12.00,6.50,1.22,1.44,2.75,11.68,6.53,1.26,1.49,2.77
2,10/08/2019,15:00,Bournemouth,Sheffield United,1.95,3.60,3.60,1.90,1.90,2.04,3.57,3.90,1.96,1.96
3,10/08/2019,15:00,Burnley,Southampton,2.62,3.20,2.75,2.10,1.72,2.71,3.31,2.81,2.17,1.77
4,10/08/2019,15:00,Crystal Palace,Everton,3.00,3.25,2.37,2.20,1.66,3.21,3.37,2.39,2.23,1.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,26/07/2020,16:00,Leicester,Man United,3.25,3.50,2.20,1.90,1.90,3.25,3.51,2.28,1.88,2.03
376,26/07/2020,16:00,Man City,Norwich,1.08,11.00,26.00,1.22,4.33,1.08,13.10,30.22,1.21,4.76
377,26/07/2020,16:00,Newcastle,Liverpool,7.50,5.25,1.36,1.53,2.50,7.79,5.07,1.41,1.53,2.65
378,26/07/2020,16:00,Southampton,Sheffield United,2.15,3.50,3.30,1.90,1.90,2.18,3.54,3.46,1.86,2.06
379,26/07/2020,16:00,West Ham,Aston Villa,3.00,3.60,2.30,1.66,2.20,3.12,3.62,2.31,1.67,2.34

In [8]:
import pandas as pd
import glob

base_url = "./data/Premier_League_{}.csv"
seasons = ["1820", "1920","2021","2122", "2223", "2324"] # Add more seasons as needed
year = []

# Create an empty list to store the dataframes
dfs = []

# Loop through the seasons and read the csv files
for season in seasons:
    file_path = base_url.format(season)
    df = pd.read_csv(file_path, usecols=columns_to_select)
    # Add a column with the season number that is determined my seaons first two digit , so it should be 23 -> 2023
    df["Season"] = "20" + season[:2]
    
    dfs.append(df)

# Concatenate the dataframes on index
result = pd.concat(dfs, ignore_index=True)

In [9]:
result.shape

(2010, 15)

In [10]:
result

,Date,Time,HomeTeam,AwayTeam,B365H,B365D,B365A,PSH,PSD,PSA,B365>2.5,B365<2.5,P>2.5,P<2.5,Season
0,09/08/2019,20:00,Liverpool,Norwich,1.14,10.00,19.00,1.15,9.59,18.05,1.40,3.00,1.40,3.11,2018
1,10/08/2019,12:30,West Ham,Man City,12.00,6.50,1.22,11.68,6.53,1.26,1.44,2.75,1.49,2.77,2018
2,10/08/2019,15:00,Bournemouth,Sheffield United,1.95,3.60,3.60,2.04,3.57,3.90,1.90,1.90,1.96,1.96,2018
3,10/08/2019,15:00,Burnley,Southampton,2.62,3.20,2.75,2.71,3.31,2.81,2.10,1.72,2.17,1.77,2018
4,10/08/2019,15:00,Crystal Palace,Everton,3.00,3.25,2.37,3.21,3.37,2.39,2.20,1.66,2.23,1.74,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005,04/11/2023,15:00,Sheffield United,Wolves,3.80,3.50,2.00,3.91,3.68,1.97,1.91,1.99,1.91,1.98,2023
2006,04/11/2023,17:30,Newcastle,Arsenal,2.80,3.20,2.60,2.83,3.41,2.59,1.95,1.95,1.95,1.93,2023
2007,05/11/2023,14:00,Nott'm Forest,Aston Villa,4.20,3.75,1.85,4.17,3.76,1.89,1.73,2.08,1.78,2.13,2023
2008,05/11/2023,16:30,Luton,Liverpool,12.00,6.50,1.22,11.23,6.76,1.24,1.36,3.10,1.39,3.06,2023
2009,06/11/2023,20:00,Tottenham,Chelsea,2.00,3.75,3.50,2.14,3.73,3.34,1.70,2.10,1.74,2.18,2023

In [11]:
result.groupby("Season").count()

,Date,Time,HomeTeam,AwayTeam,B365H,B365D,B365A,PSH,PSD,PSA,B365>2.5,B365<2.5,P>2.5,P<2.5
Season,,,,,,,,,,,,,,
2018,380,380,380,380,380,380,380,380,380,380,380,380,380,380
2019,380,380,380,380,380,380,380,380,380,380,380,380,380,380
2020,380,380,380,380,380,380,380,380,380,380,380,380,380,380
2021,380,380,380,380,380,380,380,380,380,380,379,379,380,380
2022,380,380,380,380,380,380,380,380,380,380,380,380,379,379
2023,110,110,110,110,110,110,110,110,110,110,110,110,110,110

In [12]:
# save the data
result.to_csv("./data/football_data.csv", index=False)